spring:
  mail:
    host: smtp.gmail.com
    username: juniper0917@gmail.com
    port: 587
    password: 'klcciuxsswboqnvo'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:/mybatis/mapper/**/*.xml
    username: root
    jdbc-url: jdbc:mariadb://152.67.213.248:3306/sshdesktop?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    password: oslab
  data:
    redis:
      host: 144.24.78.122
      port: 6379
      password: oslab
jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

server:
  port: 8081
#  address: 10.0.0.219


