spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1209fb2c41eef396f44f
            client-secret: 5f247ee76604f1599e075433643912d846b6fe99
  mail:
    host: smtp.gmail.com
    username: juniper0917@gmail.com
    port: 587
    password: 'klcciuxsswboqnvo'
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    mapper-locations: classpath:/mybatis/mapper/**/*.xml
    username: root
    jdbc-url: jdbc:mariadb://shade-mariadb:3306/shade?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    password: rootroot
  data:
    redis:
      host: shade-redis
      port: 6379
jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

server:
  port: 8081


